# Generated by Django 5.2.1 on 2025-11-17 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img_src', models.URLField(blank=True, null=True)),
                ('years_of_age', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('works', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=125)),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img_src', models.URLField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('short_desc', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author')),
            ],
            options={
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='books.book')),
            ],
            options={
                'db_table': 'book_detail',
            },
        ),
    ]
